SELECT DISTINCT c.CUST_F_NAME, c.CUST_L_NAME, c.CUST_PHONE
FROM CUSTOMER c
JOIN ORDERS o ON c.CUST_ID = o.CUST_ID
JOIN ORDER_LINE ol ON o.ORDER_ID = ol.ORDER_ID
JOIN PRODUCT p ON ol.UPC = p.UPC
WHERE p.UPC = 123455;