SELECT EMPLOYEE_SSN, EMPLOYEE_F_NAME, 
       EMPLOYEE_L_NAME, EMPLOYEE_HOUR_RATE, EMPLOYEE_HOUR_WORKED,
        CASE 
                WHEN EMPLOYEE_HOUR_WORKED > 40 
                        THEN (EMPLOYEE_HOUR_RATE * 40) + ((EMPLOYEE_HOUR_WORKED - 40) * (EMPLOYEE_HOUR_RATE * 1.5))
                ELSE EMPLOYEE_HOUR_WORKED * EMPLOYEE_HOUR_RATE
        END AS WEEKLY_PAYMENT
FROM EMPLOYEE;              