SELECT p.PAYMENT_ID, p.PAYMENT_CARD_NUM, c.CUST_F_NAME, c.CUST_L_NAME, o.ORDER_DATE
FROM PAYMENT p
JOIN CUSTOMER c ON p.CUST_ID = c.CUST_ID
JOIN ORDERS o ON c.CUST_ID = o.CUST_ID
WHERE o.ORDER_DATE >= (SYSDATE - 30);