SELECT
    p.PRODUCT_NAME,
    p.PRODUCT_AMT,
    P.PRODUCT_THRESHOLD,
    p.PRODUCT_UNIT_PRICE,
    sp.SUPPLIER_NAME,
    st.STORE_NAME
FROM
    PRODUCT p
JOIN
    PROD_SUPPLIER ps ON p.UPC = ps.UPC
JOIN
    SUPPLIER sp ON ps.SUPPLIER_ID = sp.SUPPLIER_ID
JOIN
    STORES st ON sp.SUPPLIER_ID = st.SUPPLIER_ID
WHERE
    st.STORE_ID = '4444440' AND p.PRODUCT_AMT < p.PRODUCT_THRESHOLD;